project_id = "mixunsevvfenajctpdfq"

[functions.fetch-topus-data]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = true

[functions.fetch-hismart-data]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.chat-stream]
verify_jwt = true

[functions.chat-suggestions]
verify_jwt = true

[functions.generate-clinical-map]
verify_jwt = true

[functions.generate-paraclinicos]
verify_jwt = true

[functions.generate-diagnostic-aids]
verify_jwt = true

[functions.generate-medicamentos]
verify_jwt = true

[functions.generate-body-analysis]
verify_jwt = true

[functions.generate-chat-title]
verify_jwt = true
