project_id = "mixunsevvfenajctpdfq"

[functions.send-email]
verify_jwt = false

[functions.validar-rethus]
verify_jwt = true

[functions.extract-document-data]
verify_jwt = false

[functions.fetch-topus-data]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = true

[functions.fetch-hismart-data]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.chat-stream]
verify_jwt = true

[functions.chat-suggestions]
verify_jwt = true

[functions.generate-clinical-map]
verify_jwt = true

[functions.generate-paraclinicos]
verify_jwt = true

[functions.generate-diagnostic-aids]
verify_jwt = true

[functions.generate-medicamentos]
verify_jwt = true

[functions.generate-body-analysis]
verify_jwt = true

[functions.generate-chat-title]
verify_jwt = true

[functions.admin-create-patient]
verify_jwt = true

[functions.admin-create-professional]
verify_jwt = true

[functions.admin-associate-professional]
verify_jwt = true

[functions.list-clinic-professionals]
verify_jwt = true

[functions.search-patient-cascade]
verify_jwt = true

[functions.create-shared-access]
verify_jwt = true

[functions.validate-shared-access]
verify_jwt = false

[functions.revoke-shared-access]
verify_jwt = true

[functions.get-shared-accesses]
verify_jwt = true
