steps:
  # Just show node version (sanity)
  - name: 'node:20-alpine'
    entrypoint: node
    args: ['-v']

  # Deploy from source using Cloud Buildpacks (no Dockerfile)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--source'
      - '.'
      - '--region'
      - 'northamerica-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--set-build-env-vars'
      - 'VITE_SUPABASE_URL=$_VITE_SUPABASE_URL,VITE_SUPABASE_PUBLISHABLE_KEY=$_VITE_SUPABASE_PUBLISHABLE_KEY'

timeout: '1800s'

substitutions:
  _SERVICE_NAME: 'riskcare-pacientes-copy'
  _VITE_SUPABASE_URL: ''
  _VITE_SUPABASE_PUBLISHABLE_KEY: ''
